### ISSUE TITLE
Not building with latest esp-idf

### ISSUE THREAD

**Issue by bastianhjaeger** [TobleMiner/mk_esp32fat#5]
esp-idf commit 3a9228fa02e933a28b15a335480fcc5e6f9d567a
mk_esp32fat 53f51c34672859af72ba72033b726a742b6a3c0a

Make not working
```
user@dev-host:~/dev/official/mk_esp32fat (master)$ make
echo  build/main.o
build/main.o
mkdir -p build 
echo precompile
precompile
cc -I. -I../src -I/home/user/dev/official/esp-idf/components/spi_flash/sim/stubs/app_update/include -I/home/user/dev/official/esp-idf/components/spi_flash/sim/stubs/driver/include -I/home/user/dev/official/esp-idf/components/spi_flash/sim/stubs/esp32/include -I/home/user/dev/official/esp-idf/components/spi_flash/sim/stubs/freertos/include -I/home/user/dev/official/esp-idf/components/spi_flash/sim/stubs/log/include -I/home/user/dev/official/esp-idf/components/spi_flash/sim/stubs/newlib/include -I/home/user/dev/official/esp-idf/components/spi_flash/sim/stubs/sdmmc/include -I/home/user/dev/official/esp-idf/components/spi_flash/sim/stubs/vfs/include -I/home/user/dev/official/esp-idf/components/soc/esp32/include -I/home/user/dev/official/esp-idf/components/esp32/include -I/home/user/dev/official/esp-idf/components/bootloader_support/include -I/home/user/dev/official/esp-idf/components/app_update/include -I/home/user/dev/official/esp-idf/components/spi_flash/include -I/home/user/dev/official/esp-idf/components/wear_levelling/include -I/home/user/dev/official/esp-idf/components/fatfs/src -I/home/user/dev/official/esp-idf/components/fatfs/test_fatfs_host/sdkconfig -I/home/user/dev/official/esp-idf/components/esp_common/include -I/home/user/dev/official/mk_esp32fat/sdkconfig/ -I/home/user/dev/official/esp-idf/tools/catch -g -m32 -ggdb  -c -o  build/main.o  src/main.c
In file included from /home/user/dev/official/esp-idf/components/spi_flash/include/esp_partition.h:22,
                 from src/main.c:11:
/home/user/dev/official/esp-idf/components/spi_flash/include/esp_flash.h:20:10: fatal error: hal/spi_flash_types.h: No such file or directory
 #include "hal/spi_flash_types.h"
          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:89: recipe for target 'build/main.o' failed
make: *** [build/main.o] Error 1
```

After some modification (see patch) I ended up with 
```
user@dev-host:~/dev/official/mk_esp32fat (master *)$ make
echo  build/main.o
build/main.o
mkdir -p build 
echo precompile
precompile
cc -I. -I../src -I/home/user/dev/official/esp-idf/components/spi_flash/sim/stubs/app_update/include -I/home/user/dev/official/esp-idf/components/spi_flash/sim/stubs/driver/include -I/home/user/dev/official/esp-idf/components/spi_flash/sim/stubs/esp32/include -I/home/user/dev/official/esp-idf/components/spi_flash/sim/stubs/freertos/include -I/home/user/dev/official/esp-idf/components/spi_flash/sim/stubs/log/include -I/home/user/dev/official/esp-idf/components/spi_flash/sim/stubs/newlib/include -I/home/user/dev/official/esp-idf/components/spi_flash/sim/stubs/sdmmc/include -I/home/user/dev/official/esp-idf/components/spi_flash/sim/stubs/vfs/include -I/home/user/dev/official/esp-idf/components/soc/include -I/home/user/dev/official/esp-idf/components/esp32/include -I/home/user/dev/official/esp-idf/components/bootloader_support/include -I/home/user/dev/official/esp-idf/components/app_update/include -I/home/user/dev/official/esp-idf/components/spi_flash/include -I/home/user/dev/official/esp-idf/components/wear_levelling/include -I/home/user/dev/official/esp-idf/components/fatfs/src -I/home/user/dev/official/esp-idf/components/fatfs/diskio -I/home/user/dev/official/esp-idf/components/fatfs/test_fatfs_host/sdkconfig -I/home/user/dev/official/esp-idf/components/esp_common/include -I/usr/include/x86_64-linux-gnu/c++/8 -I/home/user/dev/official/mk_esp32fat/sdkconfig/ -I/home/user/dev/official/esp-idf/tools/catch -DCONFIG_IDF_TARGET_ESP32=1 -g -m64 -ggdb  -DCONFIG_IDF_TARGET_ESP32=1 -c -o  build/main.o  src/main.c
src/main.c: In function ‘main’:
src/main.c:273:12: warning: implicit declaration of function ‘ff_diskio_get_drive’; did you mean ‘ff_diskio_get_pdrv_wl’? [-Wimplicit-function-declaration]
  if((err = ff_diskio_get_drive(&pdrv))) {
            ^~~~~~~~~~~~~~~~~~~
            ff_diskio_get_pdrv_wl
src/main.c:324:19: warning: format ‘%zu’ expects argument of type ‘size_t’, but argument 2 has type ‘uint32_t’ {aka ‘const unsigned int’} [-Wformat=]
  printf("Saving %zu bytes to file\n", partition->size);
                 ~~^                   ~~~~~~~~~~~~~~~
                 %u
echo postcompile
postcompile
mkdir -p build
echo "ar in: build/libmkfatfs.a"
ar in: build/libmkfatfs.a
echo "ar out: build/main.o /home/user/dev/official/mk_esp32fat/sdkconfig/sdkconfig.h"
ar out: build/main.o /home/user/dev/official/mk_esp32fat/sdkconfig/sdkconfig.h
ar rcs build/libmkfatfs.a build/main.o /home/user/dev/official/mk_esp32fat/sdkconfig/sdkconfig.h
make -C /home/user/dev/official/esp-idf/components/wear_levelling/test_wl_host lib SDKCONFIG=/home/user/dev/official/mk_esp32fat/sdkconfig/sdkconfig.h
make[1]: Entering directory '/home/user/dev/official/esp-idf/components/wear_levelling/test_wl_host'
mkdir -p build
g++ -I. -I../ -I../include -I../private_include -I../../spi_flash/sim -I../../spi_flash/sim/stubs/app_update/include -I../../spi_flash/sim/stubs/driver/include -I../../spi_flash/sim/stubs/esp32/include -I../../spi_flash/sim/stubs/freertos/include -I../../spi_flash/sim/stubs/log/include -I../../spi_flash/sim/stubs/newlib/include -I../../spi_flash/sim/stubs/sdmmc/include -I../../spi_flash/sim/stubs/vfs/include -I../../../components/esp_rom/include -I../../../components/esp_common/include -I../../../components/xtensa/include -I../../../components/xtensa/esp32/include -I../../../components/soc/soc/esp32/include -I../../../components/soc/include -I../../../components/soc/soc/include -I../../../components/esp32/include -I../../../components/bootloader_support/include -I../../../components/app_update/include -I../../../components/spi_flash/include -I/home/user/dev/official/mk_esp32fat/sdkconfig/ -I../../../tools/catch -g -m32 -I. -I../ -I../include -I../private_include -I../../spi_flash/sim -I../../spi_flash/sim/stubs/app_update/include -I../../spi_flash/sim/stubs/driver/include -I../../spi_flash/sim/stubs/esp32/include -I../../spi_flash/sim/stubs/freertos/include -I../../spi_flash/sim/stubs/log/include -I../../spi_flash/sim/stubs/newlib/include -I../../spi_flash/sim/stubs/sdmmc/include -I../../spi_flash/sim/stubs/vfs/include -I../../../components/esp_rom/include -I../../../components/esp_common/include -I../../../components/xtensa/include -I../../../components/xtensa/esp32/include -I../../../components/soc/soc/esp32/include -I../../../components/soc/include -I../../../components/soc/soc/include -I../../../components/esp32/include -I../../../components/bootloader_support/include -I../../../components/app_update/include -I../../../components/spi_flash/include -I/home/user/dev/official/mk_esp32fat/sdkconfig/ -I../../../tools/catch -std=c++11 -g -m32 -c -o  build/wear_levelling.o  ../wear_levelling.cpp
mkdir -p build

...

mkdir -p build
cc -I. -I../ -I../include -I../private_include -Istubs/app_update/include -Istubs/driver/include -Istubs/esp32/include -Istubs/esp_timer/include -Istubs/freertos/include -Istubs/log/include -Istubs/newlib/include -Istubs/sdmmc/include -Istubs/vfs/include -I../../../components/esp_rom/include -I../../../components/esp_common/include -I../../../components/xtensa/include -I../../../components/xtensa/esp32/include -I../../../components/soc/soc/esp32/include -I../../../components/soc/include -I../../../components/soc/soc/include -I../../../components/esp32/include -I../../../components/esp_timer/include -I../../../components/bootloader_support/include -I../../../components/app_update/include -I../../../components/spi_flash/include -I/home/user/dev/official/mk_esp32fat/sdkconfig/ -g -m32  -c -o  build/flash_mock_util.o  flash_mock_util.c
mkdir -p build
cc -I. -I../ -I../include -I../private_include -Istubs/app_update/include -Istubs/driver/include -Istubs/esp32/include -Istubs/esp_timer/include -Istubs/freertos/include -Istubs/log/include -Istubs/newlib/include -Istubs/sdmmc/include -Istubs/vfs/include -I../../../components/esp_rom/include -I../../../components/esp_common/include -I../../../components/xtensa/include -I../../../components/xtensa/esp32/include -I../../../components/soc/soc/esp32/include -I../../../components/soc/include -I../../../components/soc/soc/include -I../../../components/esp32/include -I../../../components/esp_timer/include -I../../../components/bootloader_support/include -I../../../components/app_update/include -I../../../components/spi_flash/include -I/home/user/dev/official/mk_esp32fat/sdkconfig/ -g -m32  -c -o  build/partition.o  ../partition.c
In file included from ../partition.c:27:
../../../components/bootloader_support/include/bootloader_common.h:176:1: error: unknown type name ‘RESET_REASON’; did you mean ‘REG_READ’?
 RESET_REASON bootloader_common_get_reset_reason(int cpu_no);
 ^~~~~~~~~~~~
 REG_READ
Makefile:62: recipe for target 'build/partition.o' failed
make[1]: *** [build/partition.o] Error 1
make[1]: Leaving directory '/home/user/dev/official/esp-idf/components/spi_flash/sim'
Makefile:45: recipe for target '/home/user/dev/official/esp-idf/components/spi_flash/sim/build/libspi_flash.a' failed
make: *** [/home/user/dev/official/esp-idf/components/spi_flash/sim/build/libspi_flash.a] Error 2

```

[patch.txt](https://github.com/TobleMiner/mk_esp32fat/files/4783217/patch.txt)

**Comment by JakubRakus** [comment]
Confirm problem. Can't build with latest esp-idf v4.2.
